name: Build Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 0'

jobs:
  build-test:
    if: github.repository == 'KemingHe/strain-seer'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: keminghe/strain-seer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Log in to the Container registry
        # Pinned 3rd party action to commit hash of release v3.4.0 on 03/14/2025 to prevent supply chain attacks
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # Pinned 3rd party action to commit hash of release v5.7.0 on 02/26/2025 to prevent supply chain attacks
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      # Add support for more platforms, i.e. linux/arm64 (macOS M1/M2) with QEMU
      - name: Set up QEMU
        # Pinned 3rd party action to commit hash of release v3.6.0 on 02/28/2025 to prevent supply chain attacks
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      # Enable advanced build features like cache export
      - name: Set up Docker Buildx
        # Pinned 3rd party action to commit hash of release v3.10.0 on 02/26/2025 to prevent supply chain attacks
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Build Docker image
        # Pinned 3rd party action to commit hash of release v6.15.0 on 02/26/2025 to prevent supply chain attacks
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}:buildcache
          cache-to: type=gha,mode=max,type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}:buildcache
          build-args: BUILD_DATE=${{ github.event.head_commit.timestamp }},VCS_REF=${{ github.sha }}
